#!/usr/bin/env php
<?php


use ApplicationItemManager\Importer\GithubImporter;


use ApplicationItemManager\LingApplicationItemManager;
use BumbleBee\Autoload\ButineurAutoloader;
use CommandLineInput\ProgramOutputAwareCommandLineInput;
use KamilleProgram\Installer\KamilleModuleInstaller;
use KamilleProgram\Installer\KamilleWidgetInstaller;
use KamilleProgram\Program\KamilleApplicationItemManagerProgram;
use KamilleProgram\Repository\KamilleModulesRepository;
use KamilleProgram\Repository\KamilleWidgetsRepository;
use Output\ProgramOutput;


$appDir = getcwd();



//--------------------------------------------
// KAMILLE MODULES AND WIDGETS
//--------------------------------------------
/**
 * To install kamille widgets, we need the kaminos environment,
 * which is booted by calling the boot script
 */
require_once $appDir . "/boot.php";


/**
 *  then we leverage the now existing butineur autoloader to load the classes
 * necessary for THIS script
 */
ButineurAutoloader::getInst()->addLocation(__DIR__ . "/class-program");




$helpFile = __DIR__ . "/class-program/help.txt";
$modulesImportDir = $appDir . "/class-modules";
$widgetsImportDir = $appDir . "/class-widgets";

$output = ProgramOutput::create();
$moduleManager = LingApplicationItemManager::create()
    ->setOutput($output)
    ->setInstaller(KamilleModuleInstaller::create()->setOutput($output)->setApplicationDirectory($appDir))
    ->bindImporter('KamilleModules', GithubImporter::create()->setGithubRepoName("KamilleModules"))
    ->setFavoriteRepositoryId('KamilleModules')
    ->setImportDirectory($modulesImportDir)
    ->addRepository(KamilleModulesRepository::create(), ["km"]);


$widgetManager = LingApplicationItemManager::create()
    ->setOutput($output)
    ->setInstaller(KamilleWidgetInstaller::create()->setOutput($output)->setApplicationDirectory($appDir))
    ->bindImporter('KamilleWidgets', GithubImporter::create()->setGithubRepoName("KamilleWidgets"))
    ->setFavoriteRepositoryId('KamilleWidgets')
    ->setImportDirectory($widgetsImportDir)
    ->addRepository(KamilleWidgetsRepository::create(), ["kw"]);


$input = ProgramOutputAwareCommandLineInput::create($argv)
    ->setProgramOutput($output)
    ->addFlag("f")
    ->addFlag("l")
    ->addFlag("v");

KamilleApplicationItemManagerProgram::create()
    ->setModuleManager($moduleManager)
    ->setWidgetManager($widgetManager)
    ->setHelpFile($helpFile)
    ->setDefaultCommand("help")
    ->setInput($input)
    ->setOutput($output)
    ->setModulesImportDirectory($modulesImportDir)
    ->setWidgetsImportDirectory($widgetsImportDir)
    ->start();
